### PR TITLE
2.8.9/feature/iconics check box

### PR DESCRIPTION
**Pull request by zTrap**
- Added support side-drawables via `xml` for `IconicsButton`
 - Added new view - `IconicsCheckBox`
 - Fixed calling wrong method in `IconicsImageView`

### CODE REVIEW

**Comment by mikepenz** [comment]
@zTrap changes look very good. 

Could you also please add some simples of them into the `PlaygroundActivity` I guess it would be really coold to showcase your new features :)

**Comment by zTrap** [comment]
Yes, sure :) Give me 5 min :)

**Comment by mikepenz** [comment]
@zTrap take your time. It will anysays also take me a bit to verify the changes.

**Comment by zTrap** [comment]
Done :)

**Comment by mikepenz** [comment]
Thank you :) I'll try to check it as soon as possible

**Comment by zTrap** [comment]
Thanks sir)

**Comment by mikepenz** [comment]
@zTrap just realized I most likely can't publish the update until my MacBook returns from repair. I have to work on windows right now, but the keys and signatures I apply on the *.aar are only on that MacBook + the TimeMachine backups :/

**Comment by zTrap** [comment]
@mikepenz no problems) You are owner and only you choose when release the updates)

**Comment by zTrap** [comment]
@mikepenz please, take your time with update. I will try to add support new checkbox attributes into checkable menu items

**Comment by mikepenz** [comment]
Thank you very much :)

**Comment by zTrap** [comment]
I'm sorry :( All my ideas to do checkable menu items doesn't worked. But in my tryes I've done refactor most pice of code. Now code more pretty :)

**Comment by mikepenz** [comment]
Don't worry. Thanks a lot for the great changes

**Comment by zTrap** [comment]
Always glad to help you :)

**Pull request merged**
