### PR TITLE
update community material icon

### PR DESCRIPTION
**Pull request by lorisgir**

### CODE REVIEW

**Comment by lorisgir** [comment]
Sorry @mikepenz I forgot to delete the old tff file and I also pushed gradle files

**Comment by mikepenz** [comment]
Thanks for the PR. I do not see changes to the enum containing the icon mappings. Where there no additions or adjustments in the new font?

**Comment by mikepenz** [comment]
Oh my bad. GitHub didn't show the full diff for that file. 
Testing now :)

**Comment by lorisgir** [comment]
Nice! 👍

Il mar 18 apr 2017, 23:19 Mike Penz <notifications@github.com> ha scritto:

**Pull request merged**
