### PR TITLE
New changes incoming :D

### PR DESCRIPTION
**Pull request by zTrap**
- Added new view - `IconicsCheckableTextView`
   Good alternative `IconicsCheckBox` with support all-sides drawables
 - New examples also added to `PlaygroundActivity`
 - Small refactoring in `IconicsImageView`

### CODE REVIEW

**Comment by mikepenz** [comment]
@zTrap oh :D nice. Thanks. 
I'll have to take a look.

**Comment by mikepenz** [comment]
@zTrap one thing which I am considering is to move all provided `views` to a seperate module. As all the custom views + their logic adds a lot on the method count, and some people may just want to use the iconics via the programatical way. (does not affect your PR :D just saying)

**Comment by zTrap** [comment]
@mikepenz yeah, I think it's best way

**Comment by zTrap** [comment]
Mike, I'm curious, how do you want to divide all the views into modules? It will be a separate library with views or each view in a separate library (and the base views can be combined into 1 library)

**Comment by mikepenz** [comment]
@zTrap well I thought to have the core library, which is just the core code, and then a addon for all the widgets. 

splitting it up more than that would get a nightmare to keep it updated :D

**Comment by zTrap** [comment]
Yes, I think also :D

**Comment by zTrap** [comment]
I made a hyphenations from the module, to simplify your work :)

**Comment by mikepenz** [comment]
@zTrap oh. Thank you really much. I absolutely appreciate this ;). 

I hope I'll be able to release it very soon for you :D

**Comment by zTrap** [comment]
@mikepenz thanks :)

**Comment by mikepenz** [comment]
@zTrap AGAIN. THANK YOU VERY MUCH :)
That'S basically your release :P

https://github.com/mikepenz/Android-Iconics#special-contributor

**Comment by zTrap** [comment]
Always glad and ready to help you=)

**Comment by mikepenz** [comment]
You are now officially part of the README :D

**Comment by zTrap** [comment]
It's really a great honor for me to be **Special contributor** of such a popular library =) Thank you very much)

**Pull request merged**
