### PR TITLE
4.0.0-rc1

### PR DESCRIPTION
**Pull request by zTrap**
- Library fully rewritten in *Kotlin* 
 - typeface libraries now have a new package name pattern: `com.mikepenz.iconics.typeface.library.<libraryname>.<TypefaceClass>`
 - updated proguard rules
 - introduced context resolving via the application `Context` using a `ContentProvider`
 - removed the required provided `Context` in some methods / classes
 - added migration information

### CODE REVIEW

**Comment by Tolriq** [comment]
There's nothing wrong in passing context :)
Please make the provider optional, 400 libraries can't add 400 providers to an app this impact startup time and hide init stuff that should not be hidden most of the time.

**Comment by Tolriq** [comment]
@mikepenz can you explicit the reaction :) It can mean a lot of different things :)

**Comment by zTrap** [comment]
@Tolriq you right and we'll make optional way to manual provide `Context` :)

**Comment by zTrap** [comment]
Code moved from fork to origin repo. Reopen PR

**Pull request closed without merging**
