### PR TITLE
Bump Community Material Typeface library to v1.1.0  (font file version: v1.1.70)

### PR DESCRIPTION
**Pull request by h6ah4i**
Bump Community Material Typeface Library to 1.1.0.

- Update TTF file to use the latest version ([v1.1.70](https://materialdesignicons.com/))

### CODE REVIEW

**Comment by mikepenz** [comment]
@h6ah4i thanks. i think you can keep the version of the addon in sync with the font version. So not changing it to v1.1.0 but to v1.1.70

**Comment by h6ah4i** [comment]
Thanks for your advice :) However, which number should I set to the `versionCode` field in `build.gradle`?

- "1.1.70" -> 1170 (???)

**Comment by mikepenz** [comment]
i think 117 should be fine ;)

**Comment by h6ah4i** [comment]
I have just fixed the version to 1.1.70 (code: 117) and rebased the branch.

**Comment by mikepenz** [comment]
@h6ah4i once again. thank you so much! :)

**Pull request merged**
