### PR TITLE
Added Proguard rules

### PR DESCRIPTION
**Pull request by medyo**
I've added Proguard rules to make library work when minification `minifyEnabled true` is enabled

### CODE REVIEW

**Comment by mikepenz** [comment]
@medyo awesome! thanks ;)

**Comment by wKovacs64** [comment]
@medyo Did you run into a situation where keeping all the `iconics` classes was needed?
```
-keep class com.mikepenz.iconics.** { *; }
```
I messed around with this before your PR and it seemed like I only needed to keep the typeface classes. Just curious what you found. Thanks.

**Comment by medyo** [comment]
Hi @wKovacs64 
Well, I didn't find any special need to keep iconics classes too, I only use it to avoid any future issues, you know proguard isn't super friendly :)

**Comment by wKovacs64** [comment]
OK, thanks.

**Pull request merged**
