### PR TITLE
Update gradle setup

### PR DESCRIPTION
**Pull request by rubengees**
This updates all dependencies and Gradle itself to latest. Moreover it applies the [android-maven-gradle-plugin](https://github.com/dcendents/android-maven-gradle-plugin), which allows to install the project to maven local. This is useful when trying to consume the project with [Jitpack](https://jitpack.io/).

### CODE REVIEW

**Comment by mikepenz** [comment]
@rubengees thanks for the PR but I think I have to decline it, as I already use a different approach to publish my project to maven, and I have no plans to provide it via jitpack

**Comment by rubengees** [comment]
This would just make it possible to use via jitpack, you don't have to. Jitpack also does have a different model, you don't release manually. Users would be able to consume via Jitpack and Jitpack would then build a release on demand without any action required from you.

If interested I could look into fixing the CI build, if not also fine, it's not that important. :)

**Comment by mikepenz** [comment]
@rubengees I know jitpack :D But that's why I disklike it. 

Jitpack does not sign the uploaded package, nor does the user know who generated that package and how it was generated. If any of the repos get's taken over or some fork with similar naming comes up. jitpack does not have any control on enforcing identity. 

I prefer uploading to jcenter and maven central as my releases are signed with a signature. and every user who includes my libraries can verify the identity of the releases and verify their integrity :) So nothing bad pops up in their apps ;)

**Comment by rubengees** [comment]
Yes, that's a good point of course. What I would propose is, that you merge this, keep releasing like usual and ignore that it is possible to use Jitpack. Interested users can then use it on their own risk.

**Comment by mikepenz** [comment]
@rubengees I understand but the reason to not do so is, because I really don't want jitpack to be used as the official releases are available via official repositories. 

If somebody wants to serve from jitpack. please create a fork and serve the fork :) 

Still thanks a lot for creating the PR :)

The changes you needed are already available by the way in 3.0.4

**Pull request closed without merging**
