### PR TITLE
WIP: add `IconicsDrawable#shadowLayer`

### PR DESCRIPTION
**Pull request by jayrave**

### CODE REVIEW

**Comment by jayrave** [comment]
Hey Mike, the shadow gets drawn but is getting clipped. I am not able to figure out why that is happening though!

Some observations:
- A paint that also draws shadow computes the same bounds for the path as a paint that doesn't carry a shadow (for all other same measures => font size, stroke width etc.)
- I tried with appropriate padding, but for some reason the shadow doesn't draw in the padding area (even though I don't see any clipping in the code!)
- I tried with both `respectFontBounds` set to `true & `false`

**Comment by mikepenz** [comment]
@jayrave your solution already works really fine. the issue you see is basically a limitation of the Android system and requires special configuration of the view. 

The `LayerType` of the view has to be defined for the `ShadowLayer` to work properly:
https://github.com/mikepenz/Android-Iconics/commit/1bde8781a24fbc0067b7d28fd7a7dc1aed788f77#diff-1b99f67d13ca2a24e395f7065f1cc374R66

We will have to think of a better API to make using the shadow not only easy, but also flexible enough. 

------------------

With my above changes to your PR the sample would result in:

**Comment by mikepenz** [comment]
Some indepth reading about this:

https://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported

**Comment by jayrave** [comment]
That makes sense! Thanks for the update & the link

**Comment by jayrave** [comment]
I'll try to come up with a way to make this user friendly (I am guessing just a warning in the JAVADOC isn't gonna cut it)

**Comment by jayrave** [comment]
Out of curiosity, how did you figure out the reason? Did you try a lot of things or have you come across a similar issue before?

**Comment by mikepenz** [comment]
Well I was first looking into the bounds as you did, but figured very quickly as applying padding did not fix it, but if I apply contour it was drawing fine. 

then I tried to just resize the text itself which didn't solve it either. 

But I then realised something. the shadow had always the color of the icon. not the color defined + I remembered something about the layer type. 

These few informations combined and a quick verification in the docs proofed my assumption ;)

**Comment by jayrave** [comment]
Nice! Thanks for the explanation :)

**Comment by mikepenz** [comment]
@jayrave merging this now as the base is correct.

**Pull request merged**
